In [2305]:
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score

In [2306]:
## we will clean some of the data
dataframe = pd.read_csv('train_u6lujuX_CVtuZ9i.csv')
dataframe.drop(['Gender','Loan_ID'], axis=1, inplace=True)
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Married            611 non-null    object 
 1   Dependents         599 non-null    object 
 2   Education          614 non-null    object 
 3   Self_Employed      582 non-null    object 
 4   ApplicantIncome    614 non-null    int64  
 5   CoapplicantIncome  614 non-null    float64
 6   LoanAmount         592 non-null    float64
 7   Loan_Amount_Term   600 non-null    float64
 8   Credit_History     564 non-null    float64
 9   Property_Area      614 non-null    object 
 10  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(6)
memory usage: 52.9+ KB


In [2307]:
dataframe['CoapplicantIncome'] = dataframe['CoapplicantIncome'].fillna(dataframe['CoapplicantIncome'].median())
dataframe['LoanAmount'] = dataframe['LoanAmount'].fillna(dataframe['LoanAmount'].median())
dataframe.head(20)

Married Dependents     Education Self_Employed  ApplicantIncome  \
0       No          0      Graduate            No             5849   
1      Yes          1      Graduate            No             4583   
2      Yes          0      Graduate           Yes             3000   
3      Yes          0  Not Graduate            No             2583   
4       No          0      Graduate            No             6000   
5      Yes          2      Graduate           Yes             5417   
6      Yes          0  Not Graduate            No             2333   
7      Yes         3+      Graduate            No             3036   
8      Yes          2      Graduate            No             4006   
9      Yes          1      Graduate            No            12841   
10     Yes          2      Graduate            No             3200   
11     Yes          2      Graduate           NaN             2500   
12     Yes          2      Graduate            No             3073   
13      No          0      Graduate            No             1853   
14     Yes          2      Graduate            No             1299   
15      No          0      Graduate            No             4950   
16      No          1  Not Graduate            No             3596   
17      No          0      Graduate            No             3510   
18     Yes          0  Not Graduate            No             4887   
19     Yes          0      Graduate           NaN             2600   

    CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0             0.00000   128.00000         360.00000         1.00000   
1          1508.00000   128.00000         360.00000         1.00000   
2             0.00000    66.00000         360.00000         1.00000   
3          2358.00000   120.00000         360.00000         1.00000   
4             0.00000   141.00000         360.00000         1.00000   
5          4196.00000   267.00000         360.00000         1.00000   
6          1516.00000    95.00000         360.00000         1.00000   
7          2504.00000   158.00000         360.00000         0.00000   
8          1526.00000   168.00000         360.00000         1.00000   
9         10968.00000   349.00000         360.00000         1.00000   
10          700.00000    70.00000         360.00000         1.00000   
11         1840.00000   109.00000         360.00000         1.00000   
12         8106.00000   200.00000         360.00000         1.00000   
13         2840.00000   114.00000         360.00000         1.00000   
14         1086.00000    17.00000         120.00000         1.00000   
15            0.00000   125.00000         360.00000         1.00000   
16            0.00000   100.00000         240.00000             NaN   
17            0.00000    76.00000         360.00000         0.00000   
18            0.00000   133.00000         360.00000         1.00000   
19         3500.00000   115.00000               NaN         1.00000   

   Property_Area Loan_Status  
0          Urban           Y  
1          Rural           N  
2          Urban           Y  
3          Urban           Y  
4          Urban           Y  
5          Urban           Y  
6          Urban           Y  
7      Semiurban           N  
8          Urban           Y  
9      Semiurban           N  
10         Urban           Y  
11         Urban           Y  
12         Urban           Y  
13         Rural           N  
14         Urban           Y  
15         Urban           Y  
16         Urban           Y  
17         Urban           N  
18         Rural           N  
19         Urban           Y

In [2308]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Married            611 non-null    object 
 1   Dependents         599 non-null    object 
 2   Education          614 non-null    object 
 3   Self_Employed      582 non-null    object 
 4   ApplicantIncome    614 non-null    int64  
 5   CoapplicantIncome  614 non-null    float64
 6   LoanAmount         614 non-null    float64
 7   Loan_Amount_Term   600 non-null    float64
 8   Credit_History     564 non-null    float64
 9   Property_Area      614 non-null    object 
 10  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(6)
memory usage: 52.9+ KB


In [2309]:
dataframe.dropna(inplace=True)
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
Index: 511 entries, 0 to 613
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Married            511 non-null    object 
 1   Dependents         511 non-null    object 
 2   Education          511 non-null    object 
 3   Self_Employed      511 non-null    object 
 4   ApplicantIncome    511 non-null    int64  
 5   CoapplicantIncome  511 non-null    float64
 6   LoanAmount         511 non-null    float64
 7   Loan_Amount_Term   511 non-null    float64
 8   Credit_History     511 non-null    float64
 9   Property_Area      511 non-null    object 
 10  Loan_Status        511 non-null    object 
dtypes: float64(4), int64(1), object(6)
memory usage: 47.9+ KB


Preparing Data

In [2310]:
from sklearn.preprocessing import OneHotEncoder
categorical_features = ['Married', 'Dependents', 'Education', 'Self_Employed','Property_Area']
x = dataframe.drop(['Loan_Status'], axis=1)
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output= False).set_output(transform= 'pandas')
ohe_x = ohe.fit_transform(x[categorical_features])
x = pd.concat([x, ohe_x], axis=1).drop(categorical_features,axis=1)
x.head(5)

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849            0.00000   128.00000         360.00000   
1             4583         1508.00000   128.00000         360.00000   
2             3000            0.00000    66.00000         360.00000   
3             2583         2358.00000   120.00000         360.00000   
4             6000            0.00000   141.00000         360.00000   

   Credit_History  Married_No  Married_Yes  Dependents_0  Dependents_1  \
0         1.00000     1.00000      0.00000       1.00000       0.00000   
1         1.00000     0.00000      1.00000       0.00000       1.00000   
2         1.00000     0.00000      1.00000       1.00000       0.00000   
3         1.00000     0.00000      1.00000       1.00000       0.00000   
4         1.00000     1.00000      0.00000       1.00000       0.00000   

   Dependents_2  Dependents_3+  Education_Graduate  Education_Not Graduate  \
0       0.00000        0.00000             1.00000                 0.00000   
1       0.00000        0.00000             1.00000                 0.00000   
2       0.00000        0.00000             1.00000                 0.00000   
3       0.00000        0.00000             0.00000                 1.00000   
4       0.00000        0.00000             1.00000                 0.00000   

   Self_Employed_No  Self_Employed_Yes  Property_Area_Rural  \
0           1.00000            0.00000              0.00000   
1           1.00000            0.00000              1.00000   
2           0.00000            1.00000              0.00000   
3           1.00000            0.00000              0.00000   
4           1.00000            0.00000              0.00000   

   Property_Area_Semiurban  Property_Area_Urban  
0                  0.00000              1.00000  
1                  0.00000              0.00000  
2                  0.00000              1.00000  
3                  0.00000              1.00000  
4                  0.00000              1.00000

In [2311]:
## maybe use OrdinalEncoder instead 
y = dataframe[['Loan_Status']]
y['Loan_Status'] = y['Loan_Status'].replace({'Y': 1, 'N': 0})
y.head()

/var/folders/g4/58ldvp712hz1n39nr7l5qpt40000gn/T/ipykernel_16897/3301250104.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y['Loan_Status'] = y['Loan_Status'].replace({'Y': 1, 'N': 0})
/var/folders/g4/58ldvp712hz1n39nr7l5qpt40000gn/T/ipykernel_16897/3301250104.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['Loan_Status'] = y['Loan_Status'].replace({'Y': 1, 'N': 0})


Loan_Status
0            1
1            0
2            1
3            1
4            1

In [2312]:
y.describe()

Loan_Status
count    511.00000
mean       0.68102
std        0.46654
min        0.00000
25%        0.00000
50%        1.00000
75%        1.00000
max        1.00000

In [2313]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=32)

In [2314]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((408, 18), (103, 18), (408, 1), (103, 1))

Feature Selection

In [2315]:
from sklearn.feature_selection import SelectKBest, chi2
sel = SelectKBest(chi2, k=5)
x_new = sel.fit_transform(x, y)
x_new.shape

(511, 5)

In [2316]:
selected_features = x.columns[sel.get_support()]
print("Selected Features:", list(selected_features))

Selected Features: ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Credit_History', 'Property_Area_Semiurban']


In [2317]:
X_train = X_train[selected_features]
#X_train.shape
#how many credit history with the value 1 have a loan status of 0


In [2318]:
X_train

ApplicantIncome  CoapplicantIncome  LoanAmount  Credit_History  \
613             4583            0.00000   133.00000         0.00000   
206             3244            0.00000    80.00000         1.00000   
208             2479            0.00000    59.00000         1.00000   
592             9357            0.00000   292.00000         1.00000   
39              3748         1668.00000   110.00000         1.00000   
..               ...                ...         ...             ...   
461             7740            0.00000   128.00000         1.00000   
376             8750         4996.00000   130.00000         1.00000   
472             4691            0.00000   100.00000         1.00000   
53              4616            0.00000   134.00000         1.00000   
258            14683         2100.00000   304.00000         1.00000   

     Property_Area_Semiurban  
613                  1.00000  
206                  0.00000  
208                  0.00000  
592                  1.00000  
39                   1.00000  
..                       ...  
461                  0.00000  
376                  0.00000  
472                  1.00000  
53                   0.00000  
258                  0.00000  

[408 rows x 5 columns]

In [2319]:
X_test = X_test[selected_features]
X_test

ApplicantIncome  CoapplicantIncome  LoanAmount  Credit_History  \
70              3208         3066.00000   172.00000         1.00000   
551             2492         2375.00000   128.00000         1.00000   
109             2071          754.00000    94.00000         1.00000   
598             9963            0.00000   180.00000         1.00000   
492             3691            0.00000   110.00000         1.00000   
..               ...                ...         ...             ...   
118             5568         2142.00000   175.00000         1.00000   
82              1378         1881.00000   167.00000         1.00000   
252             2583         2167.00000   104.00000         1.00000   
448             3340         1710.00000   150.00000         0.00000   
545             2768         1950.00000   155.00000         1.00000   

     Property_Area_Semiurban  
70                   0.00000  
551                  0.00000  
109                  1.00000  
598                  0.00000  
492                  0.00000  
..                       ...  
118                  0.00000  
82                   0.00000  
252                  0.00000  
448                  0.00000  
545                  0.00000  

[103 rows x 5 columns]

In [2320]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)  # Use same scaler for test set

In [2321]:
X_train

array([[-0.1731785 , -0.59998267, -0.17716333, -2.36233892,  1.22599653],
       [-0.37879634, -0.59998267, -0.78294763,  0.42330929, -0.815663  ],
       [-0.49627031, -0.59998267, -1.02297537,  0.42330929, -0.815663  ],
       ...,
       [-0.15659394, -0.59998267, -0.55434978,  0.42330929,  1.22599653],
       [-0.168111  , -0.59998267, -0.16573344,  0.42330929, -0.815663  ],
       [ 1.377785  ,  0.20663454,  1.77734827,  0.42330929, -0.815663  ]])

In [2322]:
X_test

array([[-3.84324527e-01,  5.77678460e-01,  2.68602472e-01,
         4.23309286e-01, -8.15662996e-01],
       [-4.94274020e-01,  3.12262987e-01, -2.34312794e-01,
         4.23309286e-01, -8.15662996e-01],
       [-5.58923093e-01, -3.10368679e-01, -6.22929137e-01,
         4.23309286e-01,  1.22599653e+00],
       [ 6.52978295e-01, -5.99982668e-01,  3.60041611e-01,
         4.23309286e-01, -8.15662996e-01],
       [-3.10154688e-01, -5.99982668e-01, -4.40050858e-01,
         4.23309286e-01, -8.15662996e-01],
       [-4.17032966e-01, -5.99982668e-01, -1.01154548e+00,
         4.23309286e-01, -8.15662996e-01],
       [-5.62915672e-01,  2.18807910e-02, -5.42919890e-01,
         4.23309286e-01, -8.15662996e-01],
       [-3.50234042e-01, -1.19853376e-01, -2.34312794e-01,
        -2.36233892e+00,  1.22599653e+00],
       [-2.84356483e-01, -5.99982668e-01, -6.00069352e-01,
         4.23309286e-01,  1.22599653e+00],
       [-2.11568691e-01,  3.41454848e-01, -4.40050858e-01,
         4.23309286e-01

In [2323]:
y_test

Loan_Status
70             1
551            1
109            1
598            1
492            1
..           ...
118            0
82             0
252            1
448            0
545            1

[103 rows x 1 columns]

K-nearest Neighbor




In [2324]:
from sklearn.neighbors import KNeighborsClassifier
dtc = KNeighborsClassifier(n_neighbors=15)
dtc.fit(X_train, y_train.values.ravel())

KNeighborsClassifier(n_neighbors=15)

In [2325]:
training_score = dtc.score(X_train, y_train.values.ravel())
print("Training Score:", training_score)
test_score =  dtc.score(X_test, y_test.values.ravel())
print("Test Score:", test_score)

Training Score: 0.8088235294117647
Test Score: 0.8155339805825242


In [2326]:
y_pred = dtc.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[17 18]
 [ 1 67]]


In [2327]:
K = []
training = []
test = []
scores = {}
for k in range(1,20):
    dtc = KNeighborsClassifier(n_neighbors=k)
    dtc.fit(X_train, y_train.values.ravel())
    training_score = dtc.score(X_train, y_train.values.ravel())
    testing_score = dtc.score(X_test, y_test.values.ravel())
    K.append(k)
    training.append(training_score)
    test.append(testing_score)
    scores[k] = [training_score, testing_score]

In [2328]:
for keys, values in scores.items():
    print(keys, ':', values)

1 : [1.0, 0.7475728155339806]
2 : [0.8529411764705882, 0.7281553398058253]
3 : [0.8504901960784313, 0.7766990291262136]
4 : [0.8357843137254902, 0.7378640776699029]
5 : [0.8455882352941176, 0.7864077669902912]
6 : [0.8284313725490197, 0.7766990291262136]
7 : [0.8357843137254902, 0.7766990291262136]
8 : [0.8357843137254902, 0.7669902912621359]
9 : [0.8259803921568627, 0.7864077669902912]
10 : [0.8259803921568627, 0.7864077669902912]
11 : [0.8284313725490197, 0.7864077669902912]
12 : [0.821078431372549, 0.7669902912621359]
13 : [0.8137254901960784, 0.7961165048543689]
14 : [0.8137254901960784, 0.7961165048543689]
15 : [0.8088235294117647, 0.8155339805825242]
16 : [0.8137254901960784, 0.7961165048543689]
17 : [0.8161764705882353, 0.8155339805825242]
18 : [0.8137254901960784, 0.7864077669902912]
19 : [0.8137254901960784, 0.7961165048543689]


LOGISTIC REGRESSION





In [2329]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=32, class_weight = 'balanced', max_iter=1000)
clf.fit(X_train, y_train.values.ravel())

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=32)

In [2330]:
clf.classes_

array([0, 1])

In [2331]:
from sklearn import metrics
y_pred_clf = clf.predict(X_test)
print (metrics.accuracy_score(y_test, y_pred_clf))

0.8155339805825242


In [2332]:
cm = confusion_matrix(y_test, y_pred_clf)
print(cm)

[[16 19]
 [ 0 68]]


In [2333]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_clf))

              precision    recall  f1-score   support

           0       1.00      0.46      0.63        35
           1       0.78      1.00      0.88        68

    accuracy                           0.82       103
   macro avg       0.89      0.73      0.75       103
weighted avg       0.86      0.82      0.79       103



In [2334]:
proba = clf.predict_proba(X_test)
#we need to have a probability higher than threshold% to predict a loan status of 1 (need to reduce false positives)
threshold = 0.57
#15
# get predictions and convert to integers
custom_pred = (proba[:,1] > threshold).astype(int)
print(confusion_matrix(y_test, custom_pred))

[[22 13]
 [16 52]]


In [2335]:
print("Custom Predictions:", custom_pred)

Custom Predictions: [0 0 1 0 1 1 1 0 1 0 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 0 0 0 1 1 1 0 0 1 1 1 1
 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1 0 1
 1 1 0 1 1 1 0 1 1 0 0 0 1 1 0 0 0 1 1 1 1 0 1 1 0 0 1 0 0]


In [2336]:
print (classification_report(y_test, custom_pred))

              precision    recall  f1-score   support

           0       0.58      0.63      0.60        35
           1       0.80      0.76      0.78        68

    accuracy                           0.72       103
   macro avg       0.69      0.70      0.69       103
weighted avg       0.72      0.72      0.72       103



In [2337]:
from sklearn.model_selection import cross_val_score, KFold
kf = KFold(n_splits=5, shuffle=True, random_state=32)
model = LogisticRegression(random_state=0)
log_reg_scores = cross_val_score(model, X_train, y_train.values.ravel(), cv=kf, scoring='accuracy')
print(log_reg_scores)

[0.81707317 0.79268293 0.82926829 0.77777778 0.79012346]


DECISION TREE

In [2338]:
from sklearn.tree import DecisionTreeClassifier
K = []
training = []
test = []
scores = {}
for k in range(1,10):
    dtc = DecisionTreeClassifier(random_state=32, max_depth= k)
    dtc.fit(X_train, y_train.values.ravel())
    training_score = dtc.score(X_train, y_train.values.ravel())
    testing_score = dtc.score(X_test, y_test.values.ravel())
    K.append(k)
    training.append(training_score)
    test.append(testing_score)
    scores[k] = [training_score, testing_score]

In [2339]:
for keys, values in scores.items():
    print(keys, ':', values)

1 : [0.803921568627451, 0.8058252427184466]
2 : [0.8063725490196079, 0.8058252427184466]
3 : [0.8137254901960784, 0.8058252427184466]
4 : [0.8235294117647058, 0.8058252427184466]
5 : [0.8284313725490197, 0.7864077669902912]
6 : [0.8651960784313726, 0.7475728155339806]
7 : [0.8799019607843137, 0.7766990291262136]
8 : [0.9068627450980392, 0.7378640776699029]
9 : [0.9240196078431373, 0.7281553398058253]


In [2340]:
from sklearn.model_selection import cross_val_score, KFold
kf = KFold(n_splits=5, shuffle=True, random_state=32)
tree = DecisionTreeClassifier(random_state=32, max_depth=3)
log_reg_scores = cross_val_score(tree, X_train, y_train.values.ravel(), cv=kf, scoring='accuracy')
print(log_reg_scores)

[0.7804878  0.79268293 0.80487805 0.7654321  0.7654321 ]


SVM

In [2341]:
from sklearn.svm import SVC
svc = SVC(kernel='linear',C=.1,gamma=1, random_state=32)
svc.fit(X_train, y_train.values.ravel())

SVC(C=0.1, gamma=1, kernel='linear', random_state=32)

In [2342]:
for i in range(1,10):
    svc = SVC(kernel='linear',C=100,gamma=i, random_state=32)
    svc.fit(X_train, y_train.values.ravel())
    training_score = svc.score(X_train, y_train.values.ravel())
    testing_score = svc.score(X_test, y_test.values.ravel())
    K.append(i)
    training.append(training_score)
    test.append(testing_score)
    scores[i] = [training_score, testing_score]
    print(i, ':', [training_score, testing_score])


1 : [0.803921568627451, 0.8058252427184466]
2 : [0.803921568627451, 0.8058252427184466]
3 : [0.803921568627451, 0.8058252427184466]
4 : [0.803921568627451, 0.8058252427184466]
5 : [0.803921568627451, 0.8058252427184466]
6 : [0.803921568627451, 0.8058252427184466]
7 : [0.803921568627451, 0.8058252427184466]
8 : [0.803921568627451, 0.8058252427184466]
9 : [0.803921568627451, 0.8058252427184466]


In [2343]:
score = svc.score(X_test, y_test.values.ravel())
print("Test Score:", score)

Test Score: 0.8058252427184466


THE FOLLOWING WILL BE WHERE ALL THE FINAL MODELS ARE ESTABLISHED

BELOW ARE THE FINAL MODELS THAT WE WILL HOOK UP TO THE API

In [2344]:
import joblib
import os 

best_k = 4  # Best k from KNN analysis
knn_model = KNeighborsClassifier(n_neighbors=best_k)
knn_model.fit(X_train, y_train.values.ravel())

KNeighborsClassifier(n_neighbors=4)

In [2345]:
log_reg = LogisticRegression(random_state=32,class_weight= 'balanced', max_iter=1000)
log_reg.fit(X_train, y_train.values.ravel())

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=32)

In [2346]:
best_depth = 3
tree_model = DecisionTreeClassifier(random_state=32, max_depth=best_depth)
tree_model.fit(X_train, y_train.values.ravel())

DecisionTreeClassifier(max_depth=3, random_state=32)

In [2347]:
#create directory for the models
import os
import joblib

# Create directory for models
output_directory = 'models'
os.makedirs(output_directory, exist_ok=True)

# Save the selected features (column names after feature selection)
joblib.dump(selected_features, os.path.join(output_directory, 'selected_features.joblib'))

# Save the StandardScaler (used to normalize the selected numeric features)
joblib.dump(scaler, os.path.join(output_directory, 'scaler.joblib'))

# Save the trained models
joblib.dump(knn_model, os.path.join(output_directory, 'knn_model.joblib'))
joblib.dump(log_reg, os.path.join(output_directory, 'log_reg_model.joblib'))
joblib.dump(tree_model, os.path.join(output_directory, 'decision_tree_model.joblib'))
joblib.dump(svc, os.path.join(output_directory, 'svc_model.joblib'))

print(f"Saved selected features, scaler, and models to '{output_directory}'")


Saved selected features, scaler, and models to 'models'


In [2354]:
#applicant income, coapplicant income, loan amount, credit history, rural, semiurban
#x_test = pd.DataFrame([[12841, 10968, 349,1, 1,]], columns=selected_features)
x_test = pd.DataFrame([[4006,1526,168,1,0]], columns= selected_features)
x_scaled = scaler.transform(x_test)
proba = log_reg.predict_proba(x_scaled)
threshold = .63
custom_pred = (proba[:,1] > threshold).astype(int)
print("Probability of Loan Approval:", custom_pred[0])

Probability of Loan Approval: 0


In [2349]:
import numpy as np
importance = np.abs(log_reg.coef_[0])
print("Feature Importances:", importance, "\nFeature Names:", selected_features)

Feature Importances: [0.04242706 0.07925368 0.10632888 1.2053562  0.40263808] 
Feature Names: Index(['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Credit_History',
       'Property_Area_Semiurban'],
      dtype='object')
